stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:20
  only:
    - tags
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - npm install
    - npm run build
    - echo "This job runs on runners with the 'violet' tag"
  artifacts:
    paths:
      - dist/
  cache:
    paths:
      - node_modules/

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
