stages:
  - build
  - deploy

variables:
  VIOLET_DEPLOY_PORT: $VIOLET_DEPLOY_PORT
  VIOLET_DEPLOY_ONLY: $VIOLET_DEPLOY_ONLY
  VIOLET_SERVER_IP: $VIOLET_SERVER_IP
  VIOLET_SERVER_USER: $VIOLET_SERVER_USER
  VIOLET_SERVER_PASSWORD: $VIOLET_SERVER_PASSWORD
  VIOLET_DEPLOY_SSH_KEY: $VIOLET_DEPLOY_SSH_KEY
  VIOLET_DOCKER_EMAIL: $VIOLET_DOCKER_EMAIL
  VIOLET_DOCKER_PASSWORD: $VIOLET_DOCKER_PASSWORD

build-job:
  stage: build
  image: node:20
  except:
    variables:
      - $VIOLET_DEPLOY_ONLY == "true"  # 当设置了这个变量时跳过构建
  only:
    - tags
  before_script:
    - export PROJECT_NAME=$(cat package.json | grep name | head -1 | awk -F "[\"]" '/name/{print$4}')
    - export BUILD_TAG=${CI_COMMIT_TAG:-latest}-$PROJECT_NAME  # 设置默认值为 latest
    - apt-get update && apt-get install -y docker.io  # 安装 Docker
    - service docker start  # 启动 Docker 服务
  script:
    - echo "Compiling the code..."
    - npm install
    - npm run build
    - echo $PROJECT_NAME
    - echo $BUILD_TAG
    - echo $VIOLET_DOCKER_EMAIL
    - echo $VIOLET_DOCKER_PASSWORD
    - docker info  # 确认 Docker 是否可用
    - echo "Login to Docker Hub"
    - echo $VIOLET_DOCKER_PASSWORD | docker login -u $VIOLET_DOCKER_EMAIL --password-stdin
    - docker build -t $VIOLET_REGISTRY/$VIOLET_DOCKER_IMAGE_NAME:$BUILD_TAG .  # 使用构建好的文件生成 Docker 镜像
    - docker push $VIOLET_REGISTRY/$VIOLET_DOCKER_IMAGE_NAME:$BUILD_TAG
  artifacts:
    paths:
      - dist/  # 保存构建产物，以便后续部署
  cache:
    paths:
      - node_modules/

deploy-job:
  stage: deploy
  image: alpine:latest
  before_script:
    - export IMAGE_NAME=chenhebin/violet-cicd-test-resp:violet-1.0.0-hotfix.24-violet-cicd-front
    - apk update && apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$VIOLET_PRIVATE_ID_RSA" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$VIOLET_SERVER_IP" >> ~/.ssh/known_hosts
  script:
    - echo "Deploying application to server..."
    - echo $VIOLET_SERVER_IP
    - echo $VIOLET_SERVER_USER
    - echo $VIOLET_DEPLOY_SSH_KEY
    - apk add --no-cache openssh
    - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $VIOLET_SERVER_USER@$VIOLET_SERVER_IP '
      docker pull $IMAGE_NAME && docker stop hello_world_cicd_container_test || true && docker rm hello_world_cicd_container_test || true && docker run -d --name hello_world_cicd_container_test -p $VIOLET_DEPLOY_PORT:$VIOLET_DEPLOY_PORT $IMAGE_NAME'
  only:
    - tags
