stages:
  - build
  - deploy

variables:
  VIOLET_DOCKER_EMAIL: $VIOLET_DOCKER_EMAIL
  VIOLET_DOCKER_PASSWORD: $VIOLET_DOCKER_PASSWORD

before_script:
  - export PROJECT_NAME=$(cat package.json | grep name | head -1 | awk -F "[\"]" '/name/{print$4}')
  - export BUILD_TAG=$CI_COMMIT_TAG-$PROJECT_NAME

build-job:
  stage: build
  image: node:20  # 第一阶段，使用 Node.js 镜像
  only:
    - tags
  script:
    - echo "Compiling the code..."
    - npm install
    - npm run build
    - echo "This job runs on runners with the 'violet' tag"
  artifacts:
    paths:
      - dist/
  cache:
    paths:
      - node_modules/

docker-build-job:
  stage: build
  image: docker:20.10.7  # 第二阶段，使用 Docker 镜像
  only:
    - tags
  script:
    - echo "Login to Docker Hub"
    - echo $VIOLET_DOCKER_PASSWORD | docker login -u $VIOLET_DOCKER_EMAIL --password-stdin
    - docker build -t $VIOLET_REGISTRY/$VIOLET_DOCKER_IMAGE_NAME:$BUILD_TAG .
    - docker push $VIOLET_REGISTRY/$VIOLET_IMAGE_NAME:$BUILD_TAG

deploy-job:
  stage: deploy
  only:
    - tags
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
