stages:
  - build
  - deploy

build-job:
  stage: build
  image: node:20
  only:
    - tags
  script:
    - npm install
    - npm run build
    - echo "This job runs on runners with the 'violet' tag"
  cache:
    paths:
      - node_modules/
